; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Apr 23 2020 12:30:36 GMT+0300 (RTZ 2 (зима))
; ================================================================================

InvStarMap:
	dc.w $0, InvStarMap_1-InvStarMap
	dc.w InvStarMap_2-InvStarMap, InvStarMap_3-InvStarMap
	dc.w InvStarMap_4-InvStarMap, InvStarMap_5-InvStarMap
	dc.w InvStarMap_6-InvStarMap, InvStarMap_7-InvStarMap
	dc.w InvStarMap_8-InvStarMap
InvStarMap_1: dc.b $1
	dc.b $F8, $0, $0, $0, $FC
InvStarMap_2: dc.b $1
	dc.b $F8, $0, $0, $1, $FC
InvStarMap_3: dc.b $1
	dc.b $F8, $1, $0, $2, $FC
InvStarMap_4: dc.b $1
	dc.b $F8, $1, $0, $4, $FC
InvStarMap_5: dc.b $1
	dc.b $F8, $1, $0, $6, $FC
InvStarMap_6: dc.b $1
	dc.b $F8, $5, $0, $8, $F8
InvStarMap_7: dc.b $1
	dc.b $F8, $5, $0, $C, $F8
InvStarMap_8: dc.b $1
	dc.b $F0, $F, $0, $10, $F0
	even